**Enrollment No :- 240840116042**

**Practical 8 | Create interactive visualizations using Plotly Express and Plotly Graph Objects**

**Step 1 : Import Required Libraries**

In [ ]:
# import pandas, plotly express, plotly graph objects
import pandas as pd
import plotly.express as ps
import plotly.graph_objects as go

**Step 2 : Create Dataset**

In [ ]:
# Create Sales Records
data = {
    "Month" : ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "Product" : ["Laptop","Mobile","Tablet","Laptop","Mobile","Tablet","Laptop","Mobile","Tablet","Laptop","Mobile","Tablet"],
    "Region" : ["North","South","East","West","North","South","East","West","North","South","East","West"],
    "Sales" : [120000, 135000, 150000, 145000, 160000, 175000, 180000, 170000, 190000, 210000, 230000, 250000],
    "Units_Sold" : [12, 30, 25, 14, 35, 30, 18, 38, 32, 21, 45, 40],
    "Profit" : [18000, 27000, 30000, 22000, 32000, 35000, 28000, 34000, 38000, 33000, 46000, 50000]
}

In [ ]:
# Convert Sales Records into DataFrame
df = pd.DataFrame(data)

In [ ]:
# Display DataFrame
df

   Month Product Region   Sales  Units_Sold  Profit
0    Jan  Laptop  North  120000          12   18000
1    Feb  Mobile  South  135000          30   27000
2    Mar  Tablet   East  150000          25   30000
3    Apr  Laptop   West  145000          14   22000
4    May  Mobile  North  160000          35   32000
5    Jun  Tablet  South  175000          30   35000
6    Jul  Laptop   East  180000          18   28000
7    Aug  Mobile   West  170000          38   34000
8    Sep  Tablet  North  190000          32   38000
9    Oct  Laptop  South  210000          21   33000
10   Nov  Mobile   East  230000          45   46000
11   Dec  Tablet   West  250000          40   50000

**Step 3 : Inspect the Dataset**

In [ ]:
# Display first five records
df.head()

  Month Product Region   Sales  Units_Sold  Profit
0   Jan  Laptop  North  120000          12   18000
1   Feb  Mobile  South  135000          30   27000
2   Mar  Tablet   East  150000          25   30000
3   Apr  Laptop   West  145000          14   22000
4   May  Mobile  North  160000          35   32000

In [ ]:
# Display the number of row and columns
df.shape

(12, 6)

In [ ]:
# Display column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Month       12 non-null     object
 1   Product     12 non-null     object
 2   Region      12 non-null     object
 3   Sales       12 non-null     int64
 4   Units_Sold  12 non-null     int64
 5   Profit      12 non-null     int64
dtypes: int64(3), object(3)
memory usage: 708.0+ bytes

**Step 4 : Create an Interactive Line Chart Using Plotly Express**

4.1 How does sales revenue change throughout the year

In [ ]:
fig = ps.line(
    df,
    x='Month',
    y='Sales',
    title='Sales vs Month'
)

fig.show()

**Step 5 : Improve the hover information**

In [ ]:
# Create a line chart using Sales over Month
# Add additional columns to the hover information. Students can see Product, Region, Units Sold
#  and Profit when they move the mouse over a data point
fig = ps.line(
    df,
    x='Month',
    y='Sales',
    title='Sales vs Month',
    hover_data=['Product','Region','Units_Sold', 'Profit']
)

fig.show()

**Step 6 :- Create an Interactive Bar Chart**

In [ ]:
# Group the dataset according to product
# Calculate the total sales generated by each product
grouped_by_product = df.groupby('Product')['Sales'].sum()

In [ ]:
# Create an interactive bar chart
fig = ps.bar(
    x=grouped_by_product.index,
    y=grouped_by_product.values,
    title='Total Sales by Product',
    labels={'x':'Product', 'y':'Total Sales'}
)

fig.show()

**Step 7 :- Interactive Scatter Plot**

In [ ]:
# To analyze the relationship between units sold and sales using an interactive scatter plot
fig = ps.scatter(
    x=df['Units_Sold'],
    y=df['Sales'],
    title='Units Sold vs Sales',
    labels={'x':'Units Sold', 'y':'Sales'}
)

fig.show()

**Step 8 :- Create an interactive Pie Chart**

In [ ]:
# To visualize regional sales contribution  using an interactive Pie Chart
fig = ps.pie(df, values='Sales', names='Region', title='Sales by Region')
fig.show()

**Step 9 :- Plotly Graph Objects**

In [ ]:
fig = go.Figure()

fig.add_trace(go.Line(
    x=df['Month'],
    y=df['Sales'],
    mode='lines+markers',
    name='Sales'
))

fig.show()

/usr/local/lib/python3.13/dist-packages/plotly/graph_objs/_deprecations.py:378: DeprecationWarning:

plotly.graph_objs.Line is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.scatter.Line
  - plotly.graph_objs.layout.shape.Line
  - etc.