**Enrollment No :- 240840116042**

**Practical No. 3 |
Apply Filtering, Sorting, Aggregation, and Group By Operations on Real-World Dataset**

In [ ]:
# Import the required modules such as pandas and Numpy
import pandas as pd
import numpy as np

**Step 1: Create a Dataframe/Records**

In [ ]:
# All fields and Values
data = {
    "Emp_ID" : [101, 102, 103, 104, 105, 106, 107, 108],
    "Name" : ["Rahul","Priya","Amit","Riya","Karan","Neha","Vivek","Pooja"],
    "Department" : ["IT","HR","IT","Finance","HR","Finance","IT","HR"],
    "City" : ["Surat","Navsari","Surat","Valsad","Surat","Navsari","Valsad","Surat"],
    "Salary":[45000, 38000, 52000, 48000, 40000, 51000, 60000, 42000],
    "Experience":[2,1,5,4,2,6,8,3]
}

In [ ]:
# Create DataFrame using pandas method
df = pd.DataFrame(data);

In [ ]:
# Display DataFrame
df

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

**Step 2: Filter Data**

2.1 Display employee from IT Department

In [ ]:
# Select only employees working in IT department
# The condition return only those row where Department is equal to "IT"
df[df["Department"] == "IT"]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

2.2 Display Employees with salary greater than 20000

In [ ]:
# Find Employees whose salary is greater than 20000 using greater than operator
df[df['Salary'] > 20000]

   Emp_ID   Name Department     City  Salary  Experience
0     101  Rahul         IT    Surat   45000           2
1     102  Priya         HR  Navsari   38000           1
2     103   Amit         IT    Surat   52000           5
3     104   Riya    Finance   Valsad   48000           4
4     105  Karan         HR    Surat   40000           2
5     106   Neha    Finance  Navsari   51000           6
6     107  Vivek         IT   Valsad   60000           8
7     108  Pooja         HR    Surat   42000           3

2.3 Display Employee from Surat

In [ ]:
# Find Employees whose city is equal to Surat using greater than operator
df[df['City'] == "Surat"]

   Emp_ID   Name Department   City  Salary  Experience
0     101  Rahul         IT  Surat   45000           2
2     103   Amit         IT  Surat   52000           5
4     105  Karan         HR  Surat   40000           2
7     108  Pooja         HR  Surat   42000           3

2.4 Apply Multiple Condition

In [ ]:
# Display employees from IT department having salary greater than 50000
df[(df['Department'] == "IT") & (df['Salary'] > 20000)]

   Emp_ID   Name Department    City  Salary  Experience
0     101  Rahul         IT   Surat   45000           2
2     103   Amit         IT   Surat   52000           5
6     107  Vivek         IT  Valsad   60000           8

**Step 3: Sorting Data**

3.1 Sort Salary in Ascending Order

In [ ]:
# Sort Salary from lowest to Highest
df.sort_values(by="Salary")

   Emp_ID   Name Department     City  Salary  Experience
1     102  Priya         HR  Navsari   38000           1
4     105  Karan         HR    Surat   40000           2
7     108  Pooja         HR    Surat   42000           3
0     101  Rahul         IT    Surat   45000           2
3     104   Riya    Finance   Valsad   48000           4
5     106   Neha    Finance  Navsari   51000           6
2     103   Amit         IT    Surat   52000           5
6     107  Vivek         IT   Valsad   60000           8

3.2 Sort Salary in descending order

In [ ]:
# Sort Salary from highest to lowest
df.sort_values(by="Salary", ascending=False)

   Emp_ID   Name Department     City  Salary  Experience
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
0     101  Rahul         IT    Surat   45000           2
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1

3.3 Sort Department Wise Salary

In [ ]:
# First Sort by department
# Within each department, sort salaries in descending order
df.sort_values(by=["Department", "Salary"], ascending=[True,False])

   Emp_ID   Name Department     City  Salary  Experience
5     106   Neha    Finance  Navsari   51000           6
3     104   Riya    Finance   Valsad   48000           4
7     108  Pooja         HR    Surat   42000           3
4     105  Karan         HR    Surat   40000           2
1     102  Priya         HR  Navsari   38000           1
6     107  Vivek         IT   Valsad   60000           8
2     103   Amit         IT    Surat   52000           5
0     101  Rahul         IT    Surat   45000           2

**Step 4: Perform Aggregation**

4.1 Calculate Total Salary

In [ ]:
# Calculate the Total Salary By Sum
df["Salary"].sum()

np.int64(376000)

4.2 Calculate the avg salary

In [ ]:
# Calculate the average salary by mean
df["Salary"].mean()

np.float64(47000.0)

4.3 Find Highest Salary

In [ ]:
# Find the highest salary by max
df['Salary'].max()

60000

4.4 Find Lowest Salary

In [ ]:
# Find the lowest salary by min
df["Salary"].min()

38000

4.5 Count Employees

In [ ]:
# Find the total employess using count method
df['Emp_ID'].count()

np.int64(8)

**Step 5:- Perform groupBy Operation**

5.1 Group Employee Based on department and Claculate the avg salary of each department

In [ ]:
# Group employees by Department
# Calculate the average salary of each department
df.groupby('Department')['Salary'].mean()

Department
Finance    49500.000000
HR         40000.000000
IT         52333.333333
Name: Salary, dtype: float64

5.2 Calculate the total salary paid by department

In [ ]:
# Group employees by Department
# Calculate the total salary of each department
df.groupby('Department')['Salary'].sum()

Department
Finance     99000
HR         120000
IT         157000
Name: Salary, dtype: int64

5.3 Display the highest salary in each department

In [ ]:
# Group employees by Department
# Calculate the highest salary of each department
df.groupby('Department')['Salary'].max()

Department
Finance    51000
HR         42000
IT         60000
Name: Salary, dtype: int64

5.4 Count Employees Department Wise

In [ ]:
# Group employees by Department
# Count Employess of each department
df.groupby('Department')['Salary'].count()

Department
Finance    2
HR         3
IT         3
Name: Salary, dtype: int64

5.5 Calculate the average salary of employees in each city

In [ ]:
# Group employees by City
# Calculate the average salary of each city
df.groupby('City')['Salary'].mean()

City
Navsari    44500.0
Surat      44750.0
Valsad     54000.0
Name: Salary, dtype: float64

**Step 6 : Multiple Aggregation Function**

In [ ]:
# Apply multiple statistical functions to the salary column for each department
df.groupby('Department')['Salary'].agg(['count', 'sum' ,'mean', 'min', 'max'])

            count     sum          mean    min    max
Department
Finance         2   99000  49500.000000  48000  51000
HR              3  120000  40000.000000  38000  42000
IT              3  157000  52333.333333  45000  60000

**Step 7 : save the result**

In [ ]:
# Save the dataset into CSV file

df.to_csv("Employee_Data.csv", index=False)

print("Dataset Saved Successfully")

Dataset Saved Successfully

**Step 8 : Download CSV File**

In [ ]:
# import the files module from Google Colab
from google.colab import files

# Download the CSV File to your computer
files.download("Employee_Data.csv")

print("CSV File Downloaded Successfully")

CSV File Downloaded Successfully