**Practical 1 | Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas**

**Step 1 : Import Pandas**

In [3]:
# Import the Pandas library under the alias 'pd' for data manipulation and analysis
import pandas as pd

In [4]:
# Define raw student dataset structured as a dictionary of lists (key = column name, value = row values)
data = {
    "ID" : [101, 102, 103, 104, 105, 106, 107],
    "Name" : ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry"],
    "Age" : [20,21,19,20,22,24,28],
    "City" : ["Surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gandhinagar", "Ahmedabad"],
    "Marks" : [85, 92, 78, 88, 81, 84, 90]
}

**Step 3: Create a DataFrame**

In [5]:
# Convert the dictionary into a 2D tabular Pandas DataFrame structure and render it
df = pd.DataFrame(data)
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Step 4 : Save Data as CSV File**

In [6]:
# Export DataFrame to a CSV file named 'student.csv' without including the default integer index
df.to_csv("student.csv", index=False)
print("CSV file created successfully")

CSV file created successfully

**Step 5 : Save Data as Excel File**

In [7]:
# Export DataFrame to an Excel file named 'student.xlsx' without saving row index numbers
df.to_excel("student.xlsx", index=False)
print("Excel file created successfully")

Excel file created successfully

**Step 6 : Save Data as JSON File**

In [8]:
# Export DataFrame to JSON format formatted as list of records with a readable 4-space indentation
df.to_json("student.json", orient="records", indent=4)
print("JSON file created successfully")

JSON file created successfully

**Read the CSV File**

In [9]:
# Read the exported CSV file back into a Pandas DataFrame and display the result
df_csv = pd.read_csv("student.csv")
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Read the Excel File**

In [10]:
# Read the exported Excel file back into a Pandas DataFrame and display the result
df_excel = pd.read_excel("student.xlsx")
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Read the JSON File**

In [11]:
# Read the exported JSON file back into a Pandas DataFrame and display the result
df_json = pd.read_json("student.json")
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Display First Five Records**

In [12]:
# Preview the top 5 rows of the DataFrame to quickly inspect initial entries
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

**Display the Last Five Records**

In [13]:
# Preview the bottom 5 rows of the DataFrame to inspect ending entries
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Step 12 : Display Dataset Info**

In [14]:
# Display detailed technical structural information (total entries, memory usage, non-null counts, and data types)
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

**Display Statistical Summary**

In [15]:
# Generate key statistical summary metrics (count, mean, std, min, max, quartiles) for all numerical columns
df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

**Step 14 : Display Dataset Shape**

In [16]:
# Return a tuple representing the total dimensions of the DataFrame as (rows, columns)
df_csv.shape

(7, 5)

**Step 15 : Display Column Names**

In [17]:
# Retrieve and display an array index of all column headers present in the DataFrame
df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step 16 : Display Data Types**

In [18]:
# Check the assigned data type (e.g., int64, object/string) for each column
df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

**Step 17 : Check for Missing Values**

In [19]:
# Identify missing/NaN values per column and return the total count of nulls for each
df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

**Step 18 : Display a single column**

In [20]:
# Extract and display a single column ('Name') as a Pandas Series
df_csv["Name"]

0     Rahul
1     Priya
2      Amit
3      Riya
4     Karan
5    Krisha
6     Harry
Name: Name, dtype: object

**Display Multiple Columns**

In [21]:
# Subset and display a multi-column subset ('Name' and 'Age') as a smaller DataFrame
df_csv[["Name", "Age"]]

     Name  Age
0   Rahul   20
1   Priya   21
2    Amit   19
3    Riya   20
4   Karan   22
5  Krisha   24
6   Harry   28

**Step 20 : Filter Records**

In [22]:
# Apply boolean indexing to filter and display only students scoring strictly greater than 85 marks
df_csv[df_csv['Marks'] > 85]

    ID   Name  Age       City  Marks
1  102  Priya   21    Navsari     92
3  104   Riya   20    Bharuch     88
6  107  Harry   28  Ahmedabad     90

**Step 21 : Calculate Average Marks**

In [23]:
# Compute and return the arithmetic mean of values in the 'Marks' column
df_csv['Marks'].mean()

np.float64(85.42857142857143)

**Step 22 : Sort Data**

In [24]:
# Sort and reorder the dataset rows based on the 'Marks' column in descending order (highest to lowest)
df_csv.sort_values(by='Marks', ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      Navsari     92
6  107   Harry   28    Ahmedabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

DISPLAY DF

In [25]:
# Print the unformatted plain text representation of the DataFrame to standard output
print(df_csv)

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90