**Practical 2 | Perform Data inspection, cleaning, handling, missing values, duplicate removal and data transformation using pandas**

**Step 1 : Import Pandas**

In [22]:
import pandas as pd

In [23]:
data = {
    'ID' : [101, 102, 103, 104, 104, 105,106, 107],
    "Name" : ['Rahul', 'Priya', 'Amit',None, 'Riya', 'Ajay', 'Naresh', 'Jenil'],
    "Age" : [20,21,None,20,20,22,23,28],
    "City" : ['Surat','Navsari','Surat','Bharuch','Bharuch','Navsari', 'Surat', 'Ahmedabad'],
    "Marks" : [85, None, 78,88,88,81,90,93]
}

In [24]:
df = pd.DataFrame(data)
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahmedabad   93.0

**Step 3 : Inspect the Dataset**

In [25]:
df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [26]:
#Display the last five rows of dataset
df.tail()

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahmedabad   93.0

In [27]:
# Display detailed information about of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [28]:
# Generate statistical information for numerical column
df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [29]:
# Display the dimension of dataset
df.shape

(8, 5)

In [30]:
# Display the datatypes of All Columns
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [31]:
# Display the name of all columns of Dataframe
df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

**Step 4 : Check Missing Values**

In [32]:
# Check for missing (null) values in every column
df.isnull()
# df.isnull().sum()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [33]:
# Count null values of each column
df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [34]:
#Total null values in whole dataframe

df.isnull().sum().sum()

np.int64(3)

**Step 5 : Fill Missing Values**

In [35]:
#Replace missing values in the Marks column.
# mean() calculate the average marks.
# fillna() replaces missing values with the calculated average
df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

# display the updated Dataframe
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

**Fill Missing Age**

In [36]:
# Replace missing values in Age column
# using the average age of all students
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahmedabad  93.000000

**Fill Missing Name**

In [37]:
# Replace the missing names with "Unknown"
df["Name"] = df["Name"].fillna("Unknown")
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

**Step 6 : Detect duplicate rows**

In [38]:
# Check whether each row is duplicated
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [39]:
# Count duplicate row
df.duplicated().sum()

np.int64(0)

**Step 7 : Remove Duplicate Records**

In [40]:
df = df.drop_duplicates()
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

**Step 8 : Rename a column**

In [41]:
# Rename the column "Marks" to "Score"
# inplace=True permanently updates the DataFrame

df.rename(columns={"Marks":"Score"}, inplace=True)

# Display the updated DataFrame
df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahmedabad  93.000000

**Step 9 : Change Data Type**

In [42]:
# Convert the Age column from float to integer
# This removes the decimal part after filling missing values

df['Score'] = df['Score'].astype(int)
df.dtypes

ID         int64
Name      object
Age      float64
City      object
Score      int64
dtype: object

In [43]:
# Create a new column
# Add 5 marks to the column "Score"
df['Final_Score'] = df['Score'] + 5
df

    ID     Name   Age       City  Score  Final_Score
0  101    Rahul  20.0      Surat     85           90
1  102    Priya  21.0    Navsari     86           91
2  103     Amit  22.0      Surat     78           83
3  104  Unknown  20.0    Bharuch     88           93
4  104     Riya  20.0    Bharuch     88           93
5  105     Ajay  22.0    Navsari     81           86
6  106   Naresh  23.0      Surat     90           95
7  107    Jenil  28.0  Ahmedabad     93           98

In [44]:
# Conversion of name from given case to uppercase
df['Name'] = df['Name'].str.upper()
df

    ID     Name   Age       City  Score  Final_Score
0  101    RAHUL  20.0      Surat     85           90
1  102    PRIYA  21.0    Navsari     86           91
2  103     AMIT  22.0      Surat     78           83
3  104  UNKNOWN  20.0    Bharuch     88           93
4  104     RIYA  20.0    Bharuch     88           93
5  105     AJAY  22.0    Navsari     81           86
6  106   NARESH  23.0      Surat     90           95
7  107    JENIL  28.0  Ahmedabad     93           98

In [45]:
# Conversion of city from given case to lowercase
df['City'] = df['City'].str.lower()
df

    ID     Name   Age       City  Score  Final_Score
0  101    RAHUL  20.0      surat     85           90
1  102    PRIYA  21.0    navsari     86           91
2  103     AMIT  22.0      surat     78           83
3  104  UNKNOWN  20.0    bharuch     88           93
4  104     RIYA  20.0    bharuch     88           93
5  105     AJAY  22.0    navsari     81           86
6  106   NARESH  23.0      surat     90           95
7  107    JENIL  28.0  ahmedabad     93           98

In [46]:
# Removing extra space
df['City'] = df['City'].str.strip()
df

    ID     Name   Age       City  Score  Final_Score
0  101    RAHUL  20.0      surat     85           90
1  102    PRIYA  21.0    navsari     86           91
2  103     AMIT  22.0      surat     78           83
3  104  UNKNOWN  20.0    bharuch     88           93
4  104     RIYA  20.0    bharuch     88           93
5  105     AJAY  22.0    navsari     81           86
6  106   NARESH  23.0      surat     90           95
7  107    JENIL  28.0  ahmedabad     93           98

In [49]:
# sorting the data based on "Final Score"
df.sort_values(by="Final_Score", ascending=False)

    ID     Name   Age       City  Score  Final_Score
7  107    JENIL  28.0  ahmedabad     93           98
6  106   NARESH  23.0      surat     90           95
3  104  UNKNOWN  20.0    bharuch     88           93
4  104     RIYA  20.0    bharuch     88           93
1  102    PRIYA  21.0    navsari     86           91
0  101    RAHUL  20.0      surat     85           90
5  105     AJAY  22.0    navsari     81           86
2  103     AMIT  22.0      surat     78           83

In [50]:
# Save the clean dataset
df.to_csv("clean_student_data.csv", index=False)
print("Dataset saved successfully")

Dataset saved successfully