**Practical 1 | Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas**

**Step 1 : Import Pandas**

In [ ]:
import pandas as pd

In [ ]:
data = {
    "ID" : [101, 102, 103, 104, 105, 106, 107],
    "Name" : ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry"],
    "Age" : [20,21,19,20,22,24,28],
    "City" : ["Surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gandhinagar", "Ahmedabad"],
    "Marks" : [85, 92, 78, 88, 81, 84, 90]
}

**Step 3: Create a DataFrame**

In [ ]:
df = pd.DataFrame(data)
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Step 4 : Save Data as CSV File**

In [ ]:
df.to_csv("student.csv", index=False)
print("CSV file created successfully")

CSV file created successfully

**Step 5 : Save Data as Excel File**

In [ ]:
df.to_excel("student.xlsx", index=False)
print("Excel file created successfully")

Excel file created successfully

**Step 6 : Save Data as JSON File**

In [ ]:
df.to_json("student.json", orient="records", indent=4)
print("JSON file created successfully")

JSON file created successfully

**Read the CSV File**

In [ ]:
df_csv = pd.read_csv("student.csv")
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Read the Excel File**

In [ ]:
df_excel = pd.read_excel("student.xlsx")
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Read the JSON File**

In [ ]:
df_json = pd.read_json("student.json")
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90

**Display First Five Records**

In [ ]:
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

**Display the Last Five Records**

In [ ]:
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahmedabad     90